[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.8", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.17"
rayon = "1.7.0"
reqwest = { version = "0.11.14", features = ["blocking"] }
scraper = "0.15.0"
serde = { version = "1.0.156", features = ["derive"] }
serde_json = "1.0.94"
uuid = { version = "1.3.0", features = ["v5"] }
